// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frxqmecqsebzvxytgrgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyeHFtZWNxc2VienZ4eXRncmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMjUzMTIsImV4cCI6MjA2MTgwMTMxMn0.zOTfE8lzvzawBwQZdZEQHkC3v7FiNyYLkm8m2BptnQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);